/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AreaBalasts.java
 *
 * Created on 23-abr-2012, 5:05:41
 */
package com.isolux.view;

import com.isolux.bo.Balasto;
import com.isolux.control.RealTimeControl;
import com.isolux.dao.properties.PropHandler;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.util.Set;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;

/**
 *
 * @author EAFIT
 */
public class AreaBalasts extends javax.swing.JFrame {

    private HashMap<String, Balasto> balasts;
    private ArrayList<Integer> selectedBalasts;
    private String areaName;
    private PpalView ppalView;
    
    /** Creates new form AreaBalasts */
    public AreaBalasts() {
        applicationTheme();
        initComponents();
        
        showBalsts();
    }
    
    public AreaBalasts(HashMap<String, Balasto> balasts, ArrayList<Integer> selectedBalasts, String areaName, PpalView ppalView) {
        this.balasts = balasts;
        this.selectedBalasts = selectedBalasts;
        this.areaName = areaName;
        this.ppalView = ppalView;
        
        applicationTheme();
        initComponents();
        jLabel2.setText(areaName);
        showBalsts();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Balastos por área");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Area:");

        jLabel2.setText("#");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Balastos por área"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Balasto", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Saves the selected balasts.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveSelectedBalasts();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Cancel the action.
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * Save selected balasts.
     */
    private void showBalsts(){
        
        DefaultTableModel balastsTable = (DefaultTableModel) jTable1.getModel();
        ArrayList<Integer> selected = PropHandler.getAreaBalasts(areaName);

        Set<String> balastsNumbers = this.balasts.keySet();
        jTable1.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(new JCheckBox()));
        
        for (String number : balastsNumbers) {
            Balasto readed = this.balasts.get(number);
            boolean isSelected = false;
            
            if (selected.contains(readed.getBalastNumber()) ){
              isSelected = true; 
            } 
            
            Object nuevo[] = {readed.getBalastNumber(), readed.getName(), isSelected};
            balastsTable.addRow(nuevo);
        }
    }
    
    
    /**
     * Save the selected balasts.
     */
    private void saveSelectedBalasts(){
        DefaultTableModel tablaTareas = (DefaultTableModel) jTable1.getModel();
        int noFilas = jTable1.getRowCount();
        ArrayList<Integer> selectedBalasts = new ArrayList<Integer>();

        for (int i = 0; i < noFilas; i++) {
            boolean isSelected = (Boolean)tablaTareas.getValueAt(i, 2);
            if (isSelected) {
                int noBalastoSeleccionado = Integer.parseInt(tablaTareas.getValueAt(i, 0).toString());
                selectedBalasts.add(noBalastoSeleccionado);
            }
        }
        
        if (selectedBalasts.size() == 0) {
            selectedBalasts.add(-1);
        }
        PropHandler.addBalasts(areaName, selectedBalasts);
        new RealTimeControl().showBalastos(ppalView);
        
        this.dispose();
    }
    
    /**
     * Sets the application theme
     */
    protected void applicationTheme() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            Logger.getLogger(AreaBalasts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
